parameters:
#    chen_xi_tag.example.class: ChenXi\TagBundle\Example

services:
#    chen_xi_tag.example:
#        class: %chen_xi_tag.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
