chen_xi_layout:
    type: rest
    resource: "@ChenXiLayoutBundle/Resources/config/routing.yml"
    prefix:   /



chen_xi_tag:
    resource: "@ChenXiTagBundle/Resources/config/routing.yml"
    prefix:   /

chen_xi_content:
    resource: "@ChenXiContentBundle/Resources/config/routing.yml"
    prefix:   /

chen_xi_main:
    resource: "@ChenXiMainBundle/Resources/config/routing.yml"
    prefix:   /

chen_xi_user:
    resource: "@ChenXiUserBundle/Resources/config/routing.yml"
    prefix:   /



