parameters:
#    chen_xi_user.example.class: ChenXi\UserBundle\Example

services:
   # chen_xi_user.example:
   #     class: %chen_xi_user.example.class%
   #     arguments: [@service_id, "plain_value", %parameter%]

   chenxi_listener.login:
       class: ChenXi\UserBundle\EventListener\SecurityListener
       arguments: [@security.context, @session]
       tags: 
           - {name: kernel.event_listener, event: security.interactive_login, method: onSecurityInteractiveLogin}