parameters:
#    chen_xi_user.example.class: ChenXi\UserBundle\Example

services:
#    chen_xi_user.example:
#        class: %chen_xi_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
