content_articles:
    type:     rest
    resource: ChenXi\ContentBundle\Controller\ArticlesController
    prefix: /api/content

content_pages:
    type:     rest
    resource: ChenXi\ContentBundle\Controller\PagesController
    prefix: /api/content

content_tags:
    type: rest
    resource: ChenXi\ContentBundle\Controller\TagsController
    prefix: /api/content

content_galleries:
    type:     rest
    resource: ChenXi\ContentBundle\Controller\GalleriesController
    prefix: /api/content


# content_images:
#     type:     rest
#     resource: ChenXi\ContentBundle\Controller\ImagesController
#     prefix: /api/content




test_page:
    path: /test
    defaults: { _controller: ChenXiContentBundle:Default:test }
