parameters:
#    chen_xi_content.example.class: ChenXi\ContentBundle\Example
    chenxi_article_manager.class: ChenXi\ContentBundle\Entity\ArticleManager
    chenxi_article.class: ChenXi\ContentBundle\Entity\Article

services:
#    chen_xi_content.example:
#        class: %chen_xi_content.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]

   chenxi_article_manager:
       class: %chenxi_article_manager.class%
       arguments: [@doctrine.orm.default_entity_manager, %chenxi_article.class%]
