parameters:
#    chen_xi_content.example.class: ChenXi\ContentBundle\Example
    chenxi_article_manager.class: ChenXi\ContentBundle\Entity\ArticleManager
    chenxi_article.class: ChenXi\ContentBundle\Entity\Article
    chenxi_gallery_manager.class: ChenXi\ContentBundle\Entity\GalleryManager
    chenxi_gallery.class: ChenXi\ContentBundle\Entity\Gallery
    chenxi_image_manager.class: ChenXi\ContentBundle\Entity\ImageManager
    chenxi_image.class: ChenXi\ContentBundle\Entity\Image


services:
#    chen_xi_content.example:
#        class: %chen_xi_content.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]

    chenxi_article_manager:
        class: %chenxi_article_manager.class%
        arguments: [@doctrine.orm.default_entity_manager, %chenxi_article.class%]
    
    chenxi_gallery_manager:
        class: %chenxi_gallery_manager.class%
        arguments: [@doctrine.orm.default_entity_manager, %chenxi_gallery.class%]

    chenxi_image_manager:
        class: %chenxi_image_manager.class%
        arguments: [@doctrine.orm.default_entity_manager, %chenxi_image.class%]