parameters:
#    chen_xi_gallery.example.class: ChenXi\GalleryBundle\Example

services:
#    chen_xi_gallery.example:
#        class: %chen_xi_gallery.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
