parameters:
    chenxi_website_manager.class: ChenXi\MainBundle\Entity\WebsiteManager
    chenxi_website.class: ChenXi\MainBundle\Entity\Website

services:

   chenxi_website_manager:
       class: %chenxi_website_manager.class%
       arguments: [@doctrine.orm.default_entity_manager, %chenxi_website.class%]
