layout_page_templates:
    type:     rest
    resource: ChenXi\LayoutBundle\Controller\TemplatesController
    prefix: /api/layout


layout_column_templates:
    type:     rest
    parent:   layout_page_templates
    resource: ChenXi\LayoutBundle\Controller\ColumnsController