parameters:
#    layout.example.class: ChenXi\LayoutBundle\Example
    chenxi_page_template_manager.class: ChenXi\LayoutBundle\Entity\PageTemplateManager
    chenxi_page_template.class: ChenXi\LayoutBundle\Entity\PageTemplate

services:
#    layout.example:
#        class: %layout.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]

    chenxi_page_template_manager:
        class: %chenxi_page_template_manager.class%
        arguments: [@doctrine.orm.default_entity_manager, %chenxi_page_template.class%]
