parameters:
#    layout.example.class: ChenXi\LayoutBundle\Example
    chenxi_page_template_manager.class: ChenXi\LayoutBundle\Entity\PageTemplateManager
    chenxi_page_template.class: ChenXi\LayoutBundle\Entity\PageTemplate
    chenxi_column_template_manager.class: ChenXi\LayoutBundle\Entity\ColumnTemplateManager
    chenxi_column_template.class: ChenXi\LayoutBundle\Entity\ColumnTemplate
    chenxi_box_type_manager.class: ChenXi\LayoutBundle\Entity\BoxTypeManager
    chenxi_box_type.class: ChenXi\LayoutBundle\Entity\BoxType
    chenxi_box_type_property_manager.class: ChenXi\LayoutBundle\Entity\BoxTypePropertyManager
    chenxi_box_type_property.class: ChenXi\LayoutBundle\Entity\BoxTypeProperty
    chenxi_template_box_manager.class: ChenXi\LayoutBundle\Entity\TemplateBoxManager
    chenxi_template_box.class: ChenXi\LayoutBundle\Entity\TemplateBox

services:
    chenxi_page_template_manager:
        class: %chenxi_page_template_manager.class%
        arguments: [@doctrine.orm.default_entity_manager, %chenxi_page_template.class%]
    chenxi_column_template_manager:
        class: %chenxi_column_template_manager.class%
        arguments: [@doctrine.orm.default_entity_manager, %chenxi_column_template.class%]
    chenxi_box_type_manager:
        class: %chenxi_box_type_manager.class%
        arguments: [@doctrine.orm.default_entity_manager, %chenxi_box_type.class%]
    chenxi_box_type_property_manager:
        class: %chenxi_box_type_property_manager.class%
        arguments: [@doctrine.orm.default_entity_manager, %chenxi_box_type_property.class%]
    chenxi_template_box_manager:
        class: %chenxi_template_box_manager.class%
        arguments: [@doctrine.orm.default_entity_manager, %chenxi_template_box.class%]