parameters:
#    layout.example.class: ChenXi\LayoutBundle\Example

services:
#    layout.example:
#        class: %layout.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
